### PR TITLE
Make library compile on upcoming 0.14.0 PS release

### PR DESCRIPTION
**Pull request by JordanMartinez**
For context, see https://discourse.purescript.org/t/updating-the-ecosystem-for-upcoming-0-14-0-release/1144

### CODE REVIEW

**Review by felixmulder — APPROVED** [review]
Looks good to me! Thanks for the PR 🥳

**Comment by JordanMartinez** [comment]
Should this PR really have been merged into master? I thought it would be
better to merge it into a new branch and then merge that branch into master
once the new release is made.

**Comment by felixmulder** [comment]
Work on this is minimal, thus I'd rather keep master pointing to 0.14 and then branch off Before  this and make a major release for 0.14 🙂

I'll tag and branch no worries :)

**Comment by felixmulder** [comment]
Otherwise drop this from the package set and I'll re-add it later on - short on time for working on this right now :)

**Comment by JordanMartinez** [comment]
Ah, ok. Sounds good.

**Pull request merged**
